import java.util.Scanner; // Needing to import this class to be able to read from the keyboard.
public class Lottery_Ticket_Generator {
		
		//This Program generated lottery ticket numbers and if the user guess match with ticket number, it gives them prize.

		public static void main(String[] args) {
			
			//Declaring scanner
			Scanner input = new Scanner(System.in);
			
			//Prints a welcome message.
			System.out.println("Welcome to the charity Lottery");
			
			//Asking User for input name
			System.out.print("Enter your name:");
			
			String name = input.next();
			
			//Asking User for input lottery
			System.out.print("Pick a two-digit number:");
			
			int guess = input.nextInt();
			
			// Declare a variable for produce random numbers between 10 to 99 for lottery 
			int lottery = ((int) (Math.random() * 100*0.9)+10);
			
			
			 // Get digits from lottery
	   int lotteryDigit1 = lottery / 10;
	   int lotteryDigit2 = (lottery % 10) ;
			
	   // Get digits from guess
	   int guessDigit1 = guess / 10;
	   int guessDigit2 = (guess % 10);
			
			// Display random lottery number
	   System.out.println("The lottery number is " + lotteryDigit1 + lotteryDigit2);
			
	   // Declare if Statement if the user guess is exactly equal to the random number generated by lottery program
			if (guess == lottery) {
				
				System.out.println("Congratulations! " + name + " you win $1000");
			}
			
			// Declare if Statement if the user guess is equal to two digits of the random number generated by lottery program
			else if ((guessDigit1 == lotteryDigit2 && guessDigit2 == lotteryDigit1)
	       || (guessDigit1 == lotteryDigit2) || (guessDigit2 == lotteryDigit1)
	       || (guessDigit2 == lotteryDigit2) || (guessDigit1 == lotteryDigit1)) {
	   
				
					System.out.println("Congratulations! " + name + " you win $500");  
				
			}
			
			// Declare if Statement if the user guess is equal to one digits of the random number generated by lottery program
			else if (guessDigit1 == lotteryDigit1 || guessDigit1 == lotteryDigit2
	           || guessDigit2 == lotteryDigit1 || guessDigit2 == lotteryDigit2)
	           {
	       System.out.println("Congratulations! " + name + " you win $100");
	   } 
			
			// Declare if Statement if the user guess is not equal to the random number generated by lottery program
			else {
	       System.out.println("Sorry! " + name + " Good luck next time");
	   }
			

			  //Close the Scanner Object
		    input.close();	
			
			
		}

	}
